FROM node:20.9.0-bullseye-slim
ENV NODE_ENV=production

WORKDIR /correction

RUN mkdir -p ./src

COPY package.json yarn.lock ./
RUN yarn install --production && \
    rm -rf /usr/local/share/.cache/yarn

COPY reporters/ reporters

COPY run_correction.sh \
     copy_files.sh \
     .env \
     .babelrc \
     correct_exercise.js \
     ./

CMD ["/correction/run_correction.sh"]
